### ISSUE TITLE
ed25519 dependency crashes electron

### ISSUE THREAD

**Issue by Akuukis** [stellar/js-stellar-base#111] opened 2017-08-20 19:31 UTC
If I am using stellar-base in backend process of electron, it installs and rebuilds successfully. But in runtime at first call to ed25519 main process crashes to console with:

```
<project>/node_modules/electron/dist/electron dist/main: symbol lookup error: <project>/node_modules/ed25519/build/Release/ed25519.node: undefined symbol: SHA512
```

Here's a fork of ed25519 with some work-in-progress for electron: https://github.com/classfellow/ed25519
Maybe related: https://github.com/stellar/js-stellar-sdk/issues/78

**Comment by bartekn** [comment] 2017-08-22 10:34
Not sure if it's possible in electron but if you add `ed25519` to ignored packages, `js-stellar-base` will switch to a slower (but working) `tweetnacl` implementation of Ed25519.

I'm closing this because it's not a bug in js-stellar-base.

**Closed by bartekn** 2017-08-22 10:34 UTC

**Comment by pakokrew** [comment] 2017-08-22 10:39
I confirm that electron build works when ignoring this package.
See pakokrew/stellar-portal for an example
